# Generated by Django 3.1.4 on 2021-05-13 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_smartphone'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmartphoneDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display', models.CharField(max_length=200)),
                ('processor', models.CharField(max_length=200)),
                ('memory', models.CharField(max_length=100)),
                ('camera', models.CharField(max_length=100)),
                ('battery', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('smartphone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.smartphone')),
            ],
        ),
    ]
