# Generated by Django 3.1.4 on 2021-05-19 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='Smartphone',
            new_name='smartphone',
        ),
    ]
